Assignment5 alan and neriah
IntelliTect-Samples/EWU-CSCD379-2023-Spring pull request #128
Opened 2023-06-04 23:04 UTC by schemcharger

By Alan Rose and Neriah Graham https://red-pebble-003ab421e.3.azurestaticapps.net/

2023-06-06 16:58 UTC, CKappes-Git commented
I'm going to start working on a code review for this.

2023-06-06 17:54 UTC, CKappes-Git requested changes

2023-06-06 17:54 UTC, CKappes-Git commented on Wordle.Api/Wordle.Api/Controllers/WordController.cs
You'll need a service to get paginated words in the controller.

2023-06-06 17:54 UTC, CKappes-Git commented on wordle-web/src/views/WordEditorView.vue
> +const words = ref([
The word editor should be accessing words from the database.  It should do a paginated search for all of the words matching the search, and changes should be reflected in real time.

2023-06-15 22:01 UTC, mmwoodfo reviewed
![image](https://github.com/IntelliTect-Samples/EWU-CSCD379-2023-Spring/assets/43832670/c85a6162-8064-47c5-95f2-f21f700bdf68)

Looks like your menu option is missing?

Also, you had a few comments left by your peers regarding adding policies for your controllers.

2023-06-15 22:02 UTC, closed without merging